export const FETCH_ALL = "FETCH_ALL";
export const FETCH_PRODUCTS_SEARCH = "FETCH_PRODUCTS_SEARCH";
export const CREATE = "CREATE";
export const FETCH_A_PRODUCT = "FETCH_A_PRODUCT";

export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
